project:
  type: website

website:
  title: "Rosalind"
  navbar: 
    background: transparent
    search: true
    right: 
    - icon: github
      href: https://github.com/imkhoibui/rosalind

  sidebar:
    style: "floating"

    contents:
    - section: "Rosalind"
      contents:
        - rosalind/1_10.qmd
        - rosalind/11_20.qmd
        - rosalind/21_30.qmd
        - rosalind/31_40.qmd
        - rosalind/41_50.qmd
      
    - section: "Reading comprehension"
      contents:
        - reading/paper.qmd

    - section: "Sorting algorithms"
      contents:
        - sorting/sort.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true